Switchboard
black-river-software/urbit-webrtc pull request #4
Opened 2021-03-28 01:20 UTC by eamsden

2021-04-25 21:00 UTC, eamsden commented
@tacryt-socryp I would appreciate another review before I merge this, if you have time. I'd like to merge it tomorrow evening (4/26 EDT)

2021-04-26 03:33 UTC, tacryt-socryp commented
Will do tomorrow morning / early afternoon.

2021-04-26 19:05 UTC, tacryt-socryp requested changes
Much better!

2021-04-26 19:05 UTC, tacryt-socryp commented on switchboard/app/switchboard.hoon
> +    [%call-peer @ta ~]
indent 149

2021-04-26 19:05 UTC, tacryt-socryp commented on switchboard/app/switchboard.hoon
> +    [%uuid ~]
indent 168

2021-04-26 19:05 UTC, tacryt-socryp commented on switchboard/app/switchboard.hoon
> +      ::
this comment (and all the ones like it that are on the same indentation as the following case statement) should be dedented by two

2021-04-26 19:05 UTC, tacryt-socryp commented on switchboard/app/switchboard.hoon
> +    ::
should be dedented by one

2021-04-26 19:05 UTC, tacryt-socryp commented on switchboard/app/switchboard.hoon
> +        (remote-disconnected:helper call.u.call-state)
indent

2021-04-26 19:05 UTC, tacryt-socryp commented on switchboard/app/switchboard.hoon
> +        ?~  +.sign
indent 259-261 by one

2021-04-26 19:05 UTC, tacryt-socryp commented on switchboard/app/switchboard.hoon
> +
no new lines allowed

2021-04-26 19:05 UTC, tacryt-socryp commented on switchboard/app/switchboard.hoon
> +|_  bowl:gall
Do you use your bowl? It doesn't look like it. If you don't, then you should just write this as a core `|%`.

2021-04-26 19:05 UTC, tacryt-socryp commented on switchboard/app/switchboard.hoon
> +          :*
dedent 428-432, as `|=` has a fixed number of arguments (2)

2021-04-26 19:11 UTC, tacryt-socryp commented
Happy to call and discuss if anything is unclear as per JSON parsing (getting rid of `type` etc)

2021-04-26 19:44 UTC, tacryt-socryp commented on switchboard/app/switchboard.hoon
> +          :*
Also use `%+` for turn instead of `%:`

2021-04-28 01:08 UTC, eamsden commented on switchboard/lib/switchboard.hoon
> +        ?>  ?=  [%o *]  jon
I will probably make this a separate PR, since removing the `type` variable will also involve matching changes to the JS library

2021-04-28 01:09 UTC, eamsden commented on switchboard/lib/switchboard.hoon
> +        ((ot ~[uuid+uuid signal+signal]) jon)
The result of `ot` is a gate with a `json` sample, but we cast it to just `call-signal:switchboard`? I fear I do not yet fully understand...

2021-04-28 01:10 UTC, eamsden commented on switchboard/lib/switchboard.hoon
> +      =/  ty  (~(got by p.jon) 'type')
See above re: separate PR

2021-04-28 01:25 UTC, tacryt-socryp commented on switchboard/lib/switchboard.hoon
> +        ((ot ~[uuid+uuid signal+signal]) jon)
Ah shit, no need to cast at all. You'll get the right result if you don't do the cast

2021-04-28 02:44 UTC, merged